# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180625_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Author')),
            ],
            options={
                'verbose_name_plural': '夫人',
                'verbose_name': '夫人',
                'db_table': 'author-wife',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publicate_date'], 'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
    ]
