# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180625_0932'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author_wife',
            table='author_wife',
        ),
    ]
