# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180624_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Goods', 'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'verbose_name': 'GoodType', 'verbose_name_plural': 'GoodType'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='goods',
            table='Goods',
        ),
        migrations.AlterModelTable(
            name='goodtype',
            table='GoodType',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
